name: DevOps Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run Script
        run: |
          echo "Running system monitor"
          chmod +x system_monitor.sh
          ./system_monitor.sh
